---
- name: 7
  hosts: all

  tasks:
  - name: Add Cron Job
    cron:
      name: Run Test Script
      minute: 30
      hour: 20
      day: 15
      month: "*"
      weekday: "*" 
      user: ansible
      job: /tmp/scripts/test.sh
      disabled: true
