---
- name: 10
  hosts: all
  become: true

  tasks:
    - name: Set Password
      user:
        name: harsh
        update_password: always
        password: "{{'abcd123' | password_hash('sha512')}}"

