---
- name: 9
  hosts: all
  become: true

  tasks:
  - name: User Creation
    user:
      name: harsh
      comment: new user for QA team
      home: /home/harsh
      shell: /bin/bash
      groups: QA,harsh
        #      state: absent
        #      remove: yes
